version: '3.5'

services:
  sgredis:
    image: redis
    volumes:
      - ./redis/storage:/data
    container_name: sgredis
  sgmysql:
    image: mysql:5.7.21
    #command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    env_file:
      - ./mysql/.mysql.env
    volumes:
      - ./mysql/storage:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: sgmysql
  sgstreamsets:
    build: ./streamsets
    #command: "${SDC_DIST}/bin/streamsets" stagelibs -install="${SDC_LIBS}"
    depends_on:
      - sgmysql
    env_file:
      - ./streamsets/.streamsets.env
    ports:
      - "18630:18630"
    volumes:
      - ./streamsets/storage:/data
      - ./streamsets/pipelines:/pipelines
      - ./streamsets/errors:/errors:rw
      - ./streamsets/extras:/opt/streamsets-datacollector-3.14.0/streamsets-libs-extras
      #- ./streamsets/libs:/opt/streamsets-datacollector-3.14.0/streamsets-libs
    container_name: sgstreamsets
  sgsuperset:
    image: amancevice/superset:0.35.2
    depends_on:
      - sgmysql
      - sgredis
    env_file:
      - ./superset/.superset.env
    ports:
      - "8088:8088"
    # volumes:
    #   - ./superset:/etc/superset
    container_name: sgsuperset
  sgrails:
    build: ./rails
    command: bash -c "rm /app/tmp/pids/server.pid & /app/bin/rails s -p 3000 -b '0.0.0.0'"
    #command: rails new . --force --database=mysql
    #command: bundle install
    depends_on:
      - sgmysql
    env_file:
      - ./rails/.rails.env
    ports:
      - "3000:3000"
    volumes:
      - ./rails/datalake:/app
    env_file:
      - ./rails/.rails.env
    container_name: sgrails
networks:
  default:
    name: sgvirtual